<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>LootData</AssemblyName>
        <RootNamespace>PantheonAddons.LootData</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\PantheonAddons\LootData\LootData.cs" Link="LootData.cs" />
        <Compile Include="..\PantheonAddonLoader\NullableAttribute.cs" Link="NullableAttribute.cs" />
        <Compile Include="..\PantheonAddonLoader\NullableContextAttribute.cs" Link="NullableContextAttribute.cs" />
        <ProjectReference Include="..\PantheonAddonFramework\PantheonAddonFramework.csproj" />
        <Reference Include="Il2CppInterop.Runtime">
          <HintPath>$(GamePath)/MelonLoader/net6/Il2CppInterop.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Il2Cppmscorlib">
          <HintPath>$(GamePath)/MelonLoader/Il2CppAssemblies/Il2Cppmscorlib.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
          <HintPath>$(GamePath)/MelonLoader/Il2CppAssemblies/UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
          <HintPath>$(GamePath)/MelonLoader/Il2CppAssemblies/UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SkipDeploy)' != 'true'">
        <ItemGroup>
            <FilesToCopy Include="$(TargetDir)LootData.dll" />
        </ItemGroup>
        <MakeDir Directories="$(GamePath)/Mods/PantheonAddons" />
        <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(GamePath)/Mods/PantheonAddons" />
    </Target>

</Project>
