<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>CombatData</AssemblyName>
        <RootNamespace>PantheonAddons.CombatData</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\PantheonAddons\CombatData\CombatData.cs" Link="CombatData.cs" />
        <ProjectReference Include="..\PantheonAddonFramework\PantheonAddonFramework.csproj" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SkipDeploy)' != 'true'">
        <ItemGroup>
            <FilesToCopy Include="$(TargetDir)CombatData.dll" />
        </ItemGroup>
        <MakeDir Directories="$(GamePath)/Mods/PantheonAddons" />
        <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(GamePath)/Mods/PantheonAddons" />
    </Target>

</Project>
